@startuml
!include common.style
'DOCUMENTATION
'PLANTUML : https://plantuml.com/fr/sequence-diagram
title Sequence diagram (consultPatientFile)
center footer Centralized medical management system - Sequence Diagram
actor "User" as U
participant "Centralized\nmedical system" as S

alt while in Patient File
U -> S: selectContactInformation()
activate S
S -> S: getContactInformation()
S --> U: showContactInformation()
deactivate S
U -> S: selectMedicalHistory()
activate S
S -> S: getMedicalHistory()
S --> U: showPatientMedicalHistory()
deactivate S
U -> S: selectMedicalVisits()
activate S
S -> S: getMedicalVisits()
S --> U: showPatientMedicalVisit()
deactivate S
end

@enduml