@startuml
!include _common.style
title Adapter class diagram
center footer Adapter class diagram

class Controller {

}

interface DataAccessObject {
    +databaseQuery()
}

class SQLiteDataAccessObject {
    +databaseQuery()
}

class DBAdapter {
    -responseQuery()
    -adaptQuery()
    +databaseQuery()
}

class OtherDatabaseType{
    +otherDatabaseTypeQuery()
}

SQLiteDataAccessObject ..|> DataAccessObject
Controller .. DataAccessObject
DBAdapter --> OtherDatabaseType
DBAdapter ..|> DataAccessObject

@enduml