@startuml
!include _common.style
title Adapter sequence diagram
center footer Adapter sequence diagram

participant ": Controller" as C
participant "SQLiteDataAccessObject" as SQL
participant "DBAdapter" as Adapter
participant "OtherDatabaseType" as DB

-->C
activate C
C -> SQL : databaseQuery()
activate SQL
C <-- SQL
deactivate SQL
<--C



--> C
C -> Adapter: databaseQuery()
activate Adapter
Adapter -> Adapter : adaptQuery()
Adapter -> DB:otherDatabaseTypeQuery()
activate DB
Adapter <-- DB
deactivate DB
Adapter -> Adapter:responseQuery()
C <-- Adapter
deactivate Adapter
<--C
deactivate C

@enduml
