@startuml
!include _common.style
title Adapter sequence diagram
center footer Adapter sequence diagram

participant ": User" as D
participant "Adapter : DOA" as DOA
participant "DBConnection" as DBC
database "Database" as DB

'D -> D: requestAccess()

D -> DOA: request()
activate D
activate DOA
DOA -> DOA: convertRequest()
activate DBC
DOA -> DBC: getInstance()
DBC -> DBC:DBConnection()
DOA <-- DBC:instance
deactivate DBC
DOA -> DB:DBRequest()
activate DB
DOA <-- DB:DBResponse()
deactivate DB
DOA -> DOA:convertResponse()

D <-- DOA:response()
deactivate DOA
deactivate D

@enduml
