@startuml
!include common.style
'DOCUMENTATION
'PLANTUML : https://plantuml.com/fr/sequence-diagram
title Ramq Dossier  (Behavior)
center footer project #2 - sequence diagram (addMedicalVisit)
actor "Doctor" as D
participant userInterface as UI
'database Database as DB

D -> UI: clickAddMedicalVisitButton()
activate UI
create "p: PatientFile" as pt
UI -> pt: medicalVisitInformation()\n(medicalVisit:String)
activate pt
create "v: MedicalVisit" as v
pt -> v: addMedicalVisit()\n(medicalVisit:String)
activate v
v --> pt: v
deactivate v
UI <-- pt: v
deactivate pt
D <-- UI: display v
deactivate UI

@enduml