@startuml
!include common.style
'DOCUMENTATION
'PLANTUML : https://plantuml.com/fr/sequence-diagram
title Ramq Dossier  (Behavior)
center footer project #2 - sequence diagram (cancelModification)
actor "Doctor" as D
participant userInterface as UI

D -> UI: clickCancelModificationButton()
activate UI
create "p: PatientFile" as pt
UI -> pt: cancelModification()
activate pt
UI <-- pt: returnMessage(String)
deactivate pt
D <-- UI: showMessage(String)
deactivate UI

@enduml