@startuml
!include common.style
title RAMQ Dossier(Structure)
center footer project #2 - class diagram
'DOCUMENTATION
'PLANTUML : https://plantuml.com/fr/class-diagram

class PatientFile{
    -PatientID patientID
    -MedicalVisits[] medicalVisits
    -MedicalHistory[] medicalHistory
    --
    'PUBLIC METHODS
    --
    'PRIVATE METHODS
}



class MedicalHistory{
    -String diagnostic
    -String treatment
    -Doctor treatingDoctor
    -DatePair datePair
}

class MedicalVisit{
    -String medicalEstablishment
    -Doctor seenDoctor
    -Date visitDate
    -String diagnostic
    -String treatment
    -String visitResume
    -String notes
}

class Doctor{
    -String lastName
    -String firstName
    -String licenceNumber
    -String specialty
    -String medicalEstablishment
}

class PatientID {
    -RAMQCode ramqCode
    -String lastName
    -String firstName
    -Date date
    -String cityOfBirth
    -Gender gender
    -String[] knownParents
    -ContactInformation contactInformation
}

'class Interface{
'}

class RAMQCode{
}

class Date{
}

enum Gender{
    FEMALE,
    MALE,
    OTHER
}

'Interface -- Doctor
'Interface -- PatientFile
PatientFile --o Doctor
PatientFile  --> "1"PatientID
PatientFile  *-- "0..*"MedicalHistory
PatientFile  *-- "0..*" MedicalVisit
PatientID -- Date
PatientID -- RAMQCode
PatientID -- Gender
@enduml