@startuml
!include common.style
title RAMQ Dossier (Structure)
center footer project #2

' TODO : Methods for each class.

' Are we keeping HealthProfessional?

'class PatientRegistry {
'
'}
'PatientRegistry o-> "*" PatientFile

class PatientFile{
'    -PatientID patientID
'    -MedicalVisits[] medicalVisits
'    -MedicalHistory[] medicalHistory
    --
    'PUBLIC METHODS
    --
    'PRIVATE METHODS
    - downloadPatientFile(): PatientFile
    - cancelModifications()
}

'abstract class User{
'}
'class Patient{
'}
'abstract class HealthProfessional{
'}
'class MedicalEstablishment{
'}

class MedicalHistory{
    -String diagnostic
    -String treatment
    -Doctor treatingDoctor
'    -DatePair datePair
}

class MedicalVisit{
    -String medicalEstablishment
    -Doctor seenDoctor
'    -Date visitDate
    -String diagnostic
    -String treatment
    -String visitSummary
    -String notes
}

class Doctor{
    -String lastName
    -String firstName
    -String licenceNumber
    -String specialty
    -String medicalEstablishment

'   -searchPatientFile(date: Date): PatientFile[]
}

class PatientID {
    -String lastName
    -String firstName
'    -Date dateOfBirth
    -String cityOfBirth
    -String[] knownParents
}

class ContactInformation {
    - number: int
    - street: String
    - city: String
    - postalCode: String
    - phone: String
    - email: String
    + modifyContactInfo()
    - validatePhone(phone: String): boolean
    - validateEmail(email: String): boolean
    - validatePostalCode(code: String): boolean
}

'class Interface{
'}

class RAMQCode{
    -validateFormat(code: String): boolean
}

class Date{
    -String date
    -validateFormat(date: String): boolean
}

enum Gender{
    FEMALE,
    MALE,
    OTHER
}

'Interface -- Doctor
'Interface -- PatientFile
'HealthProfessional <|-- Doctor

Doctor o--> "manages\r*" PatientFile

PatientFile --> "1" PatientID
PatientFile *--> "0..*" MedicalHistory
PatientFile *--> "0..*" MedicalVisit

PatientID --> "1" Date
PatientID --> "1" RAMQCode
PatientID --> "1" Gender

ContactInformation "1" <- PatientID

MedicalHistory --> "1..2" Date
MedicalVisit --> "1" Date

@enduml
