@startuml
title Centralized medical management system - Class diagram
center footer Centralized medical management system - Class diagram

' TODO : Methods for each class.
' TODO : Add responsibilities? interfaces?
' TODO : clean up

class PatientRegistry {
+ search(idpatient : PatientID) : PatientFile
}
PatientRegistry o-> "*" PatientFile

interface Searchable {
+ search()
}
Searchable <|.. DoctorRegistry
Searchable <|.. PatientRegistry

class DoctorRegistry {
+ search(licenceNumber: String ) : Doctor
}
DoctorRegistry o--> "*" Doctor

class PatientFile{
'    -PatientID patientID
'    -MedicalVisits[] medicalVisits
'    -MedicalHistory[] medicalHistory
    --
    'PUBLIC METHODS
    --
    'PRIVATE METHODS
    - consultPatientFile(): PatientFile
    - cancelModifications()
}

abstract class User{
- String LastName
- String FirstName
}

class Patient{
{method}
}
PatientFile <- Patient

User <|-- Patient
User -->"1" ContactInformation


class HealthProfessional{
}

User <|-- HealthProfessional

class MedicalEstablishment{

- String IdEstablishment
- String EstablishmentName

}
MedicalEstablishment ->"1" ContactInformation
Doctor ->"1" MedicalEstablishment

class MedicalHistory{
    -String diagnostic
    -String treatment
    -Doctor treatingDoctor
'    -DatePair datePair
}

class MedicalVisit{
    -String medicalEstablishment
    -Doctor seenDoctor
'    -Date visitDate
    -String diagnostic
    -String treatment
    -String visitSummary
    -String notes
}

class Doctor{
    -String licenceNumber
    -String specialty
    -String medicalEstablishment

'   -searchPatientFile(date: Date): PatientFile[]
}

class PatientID {
    -String lastName
    -String firstName
'    -Date dateOfBirth
    -String cityOfBirth
    -String[] knownParents
}

class ContactInformation {
    - number: int
    - street: String
    - city: String
    - postalCode: String
    - phone: String
    - email: String
'    + modifyContactInfo()
    - validatePhone(phone: String): boolean
    - validateEmail(email: String): boolean
    - validatePostalCode(code: String): boolean
}

'class Interface{
'}

class RAMQCode{
    -validateFormat(code: String): boolean
}

class Date{
    -String date
    -validateFormat(date: String): boolean
}

enum Gender{
    FEMALE,
    MALE,
    OTHER
}

'Interface -- Doctor
'Interface -- PatientFile

Doctor o--> "manages\r*" PatientFile
Doctor -|> User

PatientFile --> "1" PatientID
PatientFile *--> "0..*" MedicalHistory
PatientFile *--> "0..*" MedicalVisit

PatientID --> "1" Date
PatientID --> "1" RAMQCode
PatientID --> "1" Gender

ContactInformation "1" <- PatientID

MedicalHistory --> "1..2" Date
MedicalVisit --> "1" Date

@enduml
