@startuml
!include common.style
'DOCUMENTATION
'PLANTUML : https://plantuml.com/fr/sequence-diagram
title Sequence diagram (consultPatientFile)
center footer Sequence diagram (consultPatientFile)
actor "Doctor" as D
participant "Centralized\nmedical system" as S

D -> S: clickPatientID(p: PatientFile)
activate S
S -> S: getPatientID(p)
S --> D: display id
deactivate S

D -> S: clickMedicalHistory(p: PatientFile)
activate S
S -> S: getMedicalHistory(p)
S --> D: display history
deactivate S

D -> S: clickMedicalVisits(p: PatientFile)
activate S
S -> S: getMedicalVisits()
S --> D: display visits
deactivate S

@enduml