@startuml
!include common.style
'DOCUMENTATION
'PLANTUML : https://plantuml.com/fr/sequence-diagram
title Sequence diagram (consultPatientFile)
center footer Sequence diagram (consultPatientFile)
actor "User" as U
participant "Centralized\nmedical system" as S

U -> S: clickPatientID(p: PatientFile)
activate S
S -> S: getPatientID(p)
S --> U: display id
deactivate S

U -> S: clickMedicalHistory(p: PatientFile)
activate S
S -> S: getMedicalHistory(p)
S --> U: display history
deactivate S

U -> S: clickMedicalVisits(p: PatientFile)
activate S
S -> S: getMedicalVisits()
S --> U: display visits
deactivate S

@enduml