@startuml
'DOCUMENTATION
'PLANTUML : https://plantuml.com/fr/deployment-diagram
'WHAT'S A DEPLOYEMENT DIAGRAM : https://www.lucidchart.com/pages/fr/diagramme-de-deploiement-uml
title Centralized medical management system - Deployment diagram
center footer Centralized medical management system - Deployment Diagram

database DataWarehouseServer as DW{
    storage dataWarehouse
}

database DataBaseServer as DB{
    storage database
}

node ApplicationServer as AS{
    component BackEnd

}

node WebServer as WS {
    component FrontEnd
}

node IndividualMachine as IM{
    component UserInterface
    component Browser
}


IM -[#red,dashed,thickness=4]- WS : TCP/IP
WS -[#red,dashed,thickness=4]- AS : TCP/IP
WS -[#red,dashed,thickness=4]- DB : TCP/IP
DB -[#red,dashed,thickness=4]- AS : TCP/IP
AS -[#red,dashed,thickness=4]- DW : TCP/IP

@enduml