@startuml
!include common.style
'DOCUMENTATION
'PLANTUML : https://plantuml.com/fr/sequence-diagram
title Sequence diagram (login)
center footer sequence diagram (login)
actor "User" as U
participant "Centralized\nmedical system" as S
participant "Data access\nobject" as D

U -> S: clickLoginButton\n(username: String\npassword: String)
activate S

S -> D: selectUser\n(username: String\npassword: String)
activate D
D --> S: result
deactivate D

alt success
    S --> U: profile
else error
    deactivate D
    S --> U: error
end

deactivate S

@enduml