@startuml
!include common.style
'DOCUMENTATION
'PLANTUML : https://plantuml.com/fr/sequence-diagram
title Sequence diagram (login)
center footer sequence diagram (login)
actor "User" as U
participant "Centralized\nmedical system" as S
participant "Data access\nobject" as D
database Database as DB

U -> S: login()
activate S
S -> D: authentication()
activate D
D -> DB: getUserProfile()
activate DB
D <-- DB:returnUserProfile()
deactivate DB
D --> S: returnUserProfile()
deactivate D
alt success
    S --> U: displayProfile()
else error
    deactivate D
    S --> U: displayError()
end

deactivate S

@enduml