@startuml
!include common.style
'DOCUMENTATION
'PLANTUML : https://plantuml.com/fr/sequence-diagram
title Ramq Dossier  (Behavior)
center footer project #2 - sequence diagram(addPatientFile)
actor "Doctor" as D
participant userInterface as UI
participant patientFile as PF
database Database
@enduml