@startuml
!include common.style
'DOCUMENTATION
'PLANTUML : https://plantuml.com/fr/sequence-diagram
title Sequence diagram (modifyContactInfo)
center footer Centralized medical management system - Sequence Diagram
actor "Patient" as P
participant "Centralized\nmedical system" as S
participant "Data access\nobject" as D

P -> S: updatePatientContactInfo()
S -> D: updatePatientContactInfo()
D --> S: showResult()
alt error fails to update
    S --> P: displayError()
else success
    S --> P: displaySuccess()
end


@enduml