@startuml
!include common.style
'DOCUMENTATION
'PLANTUML : https://plantuml.com/fr/sequence-diagram
title Sequence diagram (modifyContactInfo)
center footer Sequence diagram (modifyContactInfo)
actor "Patient" as P
participant "Centralized\nmedical system" as S
participant "Data access\nobject" as D
database Database as DB

P -> S: udatePatientContactInfo()
S -> D: updatePatientContactInfo()
activate DB
D -> DB: updatePatientContactInfo()
D <- DB: returnMessage()
deactivate DB
D --> S: showResult()
alt error fails to update
    S --> P: displayError()
else success
    S --> P: displaySuccess()
end


@enduml