@startuml
!include common.style
'DOCUMENTATION
'PLANTUML : https://plantuml.com/fr/sequence-diagram
title Sequence diagram (login)
center footer sequence diagram (login)
actor "Patient" as P
participant "Centralized\nmedical system" as S
participant "Data access\nobject" as D

P -> S: clickUpdateContactInfoButton\n(p: PatientFile)
activate S

S -> D: updateUser\n(p: PatientFile)
activate D
D --> S: result
deactivate D

alt success
    S --> P: display success
else error
    deactivate D
    S --> P: display error
end

deactivate S

@enduml