@startuml
!include common.style
'DOCUMENTATION
'PLANTUML : https://plantuml.com/fr/sequence-diagram

title Sequence diagram (reconstructPatientFile)
center footer sequence diagram (reconstructPatientFile)
actor "RAMQ" as R
participant "Centralized\nmedical system" as S
participant "Data access\nobject" as D
database Database as DB

R -> S: reconstructPatientFile()
activate S
S -> D: reconstructPatientFile()
activate D
D -> DB: getPatientFile()
activate DB
D <-- DB: returnPatientFile()
deactivate DB
D --> S: resultPatientFile()
deactivate D
alt success
    S --> R: showSuccessMessage()
else error
    S --> R: showFailureMessage()
end

@enduml