@startuml
!include common.style
'DOCUMENTATION
'PLANTUML : https://plantuml.com/fr/sequence-diagram
title Ramq Dossier  (Behavior)
center footer project #2 - sequence diagram (searchPatientFile)
actor "Doctor" as D
participant userInterface as UI
participant databaseInterface as DI
database Database as DB

D -> UI: clickSearchButton\n(searchCriteria: String)
activate UI

UI -> DI: searchPatientFile\n(searchCriteria: String)
activate DI

DI -> DB: SELECT query
activate DB

DB --> DI: queryResult
deactivate DB

create "p: PatientFile" as pt
DI -> pt: this(queryResult)

activate pt
pt --> DI: p
deactivate pt

alt p.patientID != null
    DI --> UI: showPatientFile(p)
    UI --> D: file
else
    DI --> UI: showError()
    deactivate DI
    UI --> D: error
end

deactivate UI

@enduml