@startuml
!include common.style
'DOCUMENTATION
'PLANTUML : https://plantuml.com/fr/sequence-diagram
title Ramq Dossier  (Behavior)
center footer project #2 - sequence diagram(login)
actor Doctor as D
participant userInterface as UI
participant databaseInterface as DI
database Database as DB

loop until success
D -> UI: clickLoginButton()\n(Username: String)\n(Password: String)
activate D
activate UI
UI -> DI: sendLoginInfo(String)\nregexVerification ()
activate DI
DI -> DB:[regex pass]\nsendLoginInfo(String)
activate DB
UI <-- DI:[regex fails]\nsendErrorMessage(String)
DB -> DB: verifyLoginInfo
DI <-- DB: returnInfoMessage(String)
deactivate DB
UI <-- DI: showAuthenticationAnswer(String)
deactivate DI
D <-- UI: [if fails] showErrorMessage(String)
D <-- UI: [if success] showSuccessMessage(String)
deactivate UI
deactivate D
end

@enduml