@startuml
!include common.style
'DOCUMENTATION
'PLANTUML : https://plantuml.com/fr/sequence-diagram
title Ramq Dossier  (Behavior)
center footer project #2 - sequence diagram(modifyPatientFile)
actor "Doctor" as D
participant userInterface as UI
participant patientFile as PF
participant databaseInterface as DI
database Database as DB

loop until file is open
D -> UI: enterNewInformation(String)
activate D
activate UI
UI -> PF: autoSave(String)
activate PF
UI <-- PF: sendSaveMessage(String)
D <-- UI: showSaveMessage(String)
end
D -> UI: closeFile()
UI -> PF: sendInfo()
PF -> DI: sendInfoToDB(String)
activate DI
activate DB
DI -> DB: saveModifToDB(String)
DB -> DB: insert new information
DI <-- DB: sendMessage(String)
deactivate DB
PF <-- DI: this()
deactivate DI
UI <-- PF: this()
deactivate PF
D <-- UI: showMessageSuccess(String)
deactivate D
deactivate UI

@enduml