@startuml
!include common.style
'DOCUMENTATION
'PLANTUML : https://plantuml.com/fr/sequence-diagram
title Ramq Dossier  (Behavior)
center footer project #2 - sequence diagram (login)
actor "Doctor" as D
participant userInterface as UI
participant databaseInterface as DI
database Database as DB

D -> UI: clickSubmitButton(p: PatientFile)
activate UI

UI -> UI: promptConfirmation()
alt No
    UI --> D
else Yes
    UI -> DI: submitChanges(p)
    activate DI

    DI -> DB: INSERT query
    activate DB

    DB --> DI
    deactivate DB

    DI --> UI

    UI --> D
end







deactivate UI

@enduml