@startuml
!include common.style
'DOCUMENTATION
'PLANT UML : https://plantuml.com/fr/sequence-diagram

:Doctor: as D
:RAMQ: as R
:Patient: as P
:HealthProfessional: as H
:OtherHealthProfessional: as O

H <|-- D
H <|- O

title RAMQ Dossier (Use Cases)
center footer use case diagram

rectangle "Medical record management system" {

    usecase login

    ' HealthProfessionals
    usecase consultPatientFile

    ' Doctor
    usecase cancelModifications
    usecase modifyPatientFile

    ' Patient
    usecase modifyContactInfo

    ' RAMQ
    usecase addPatientFile
    usecase reconstructPatientFile

    ' includes
    consultPatientFile --> "include" login
    modifyContactInfo --> login
}

' Doctor
D --> modifyPatientFile
D --> cancelModifications

' HealthProfessional
H --> consultPatientFile

' Patient
P --> consultPatientFile
P --> modifyContactInfo

' RAMQ
reconstructPatientFile <-- R
addPatientFile <- R



@enduml