@startuml
!include common.style
'DOCUMENTATION
'PLANT UML : https://plantuml.com/fr/sequence-diagram

' Thought : A Doctor can consult a patient file, and
' optionally download it or modifiy it.

' Every action requires the doctor to login.

' Brainstorm : A Doctor (technically) shouldn't be able to
' modify a patient file after it has been definitely saved,
' can cause ethical problems (falsifying medical records).
' Therefore, automatic saving can be done locally, but once
' a file is saved to the database, change cannot be undone.

:Doctor: as D
title RAMQ Dossier (Use Cases)
center footer project #2 - use case diagram
'usecase modifyContactInfo // Can the doctor do that?
'usecase modifyPatientFile
usecase login
usecase consultPatientFile
usecase cancelModifications
usecase downloadFile
usecase searchPatientFile
'usecase addPatientFile
usecase addMedicalHistory
usecase addMedicalVisit
'Will probably change

consultPatientFile <-- "extends" addMedicalHistory
consultPatientFile <-- "extends" addMedicalVisit
'modifyPatientFile --> "extends" consultPatientFile
'modifyContactInfo --> "extends" consultPatientFile
D -> consultPatientFile
consultPatientFile <-- "extends" cancelModifications

consultPatientFile <- "extends" downloadFile
searchPatientFile <-- D
'addPatientFile <-- D

login <-- "include" consultPatientFile
login <-- "include" searchPatientFile
'login "include" <-- addPatientFile

@enduml