@startuml
!include common.style
'DOCUMENTATION
'PLANT UML : https://plantuml.com/fr/sequence-diagram

:Doctor: as D
:RAMQ: as R
:Patient: as P
:HealthProfessional: as H
:OtherHealthProfessional: as O

D --|> H

O -|> H

title RAMQ Dossier (Use Cases)
center footer use case diagram

rectangle "Medical record management system" {

    usecase login

    ' HealthProfessionals
    usecase consultPatientFile

    ' Doctor
    usecase modifyPatientFile

    ' Patient
    usecase modifyContactInfo

    ' RAMQ
    usecase reconstructPatientFile

    ' includes
     reconstructPatientFile  ..> "include" login
    modifyPatientFile ..> "include" consultPatientFile
    consultPatientFile .> "include" login
    login "include" <. modifyContactInfo
    modifyPatientFile ..> "include" login
}

' Doctor
D -> modifyPatientFile

' HealthProfessional
H -> " " consultPatientFile

' Patient
consultPatientFile <- P
modifyContactInfo <- P

' RAMQ
reconstructPatientFile <- R

@enduml